# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: send_msg.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'send_msg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esend_msg.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1b\n\x08Mensagem\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"L\n\x0b\x43onfirmacao\x12\x0e\n\x06msgLen\x18\x01 \x01(\x05\x12-\n\ttimeStamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2,\n\x07SendMsg\x12!\n\x06\x45nviar\x12\t.Mensagem\x1a\x0c.Confirmacaob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'send_msg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MENSAGEM']._serialized_start=51
  _globals['_MENSAGEM']._serialized_end=78
  _globals['_CONFIRMACAO']._serialized_start=80
  _globals['_CONFIRMACAO']._serialized_end=156
  _globals['_SENDMSG']._serialized_start=158
  _globals['_SENDMSG']._serialized_end=202
# @@protoc_insertion_point(module_scope)
